services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sketch_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sketch_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.prod
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run dev

volumes:
  postgres_data:
