services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sketch_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: sketch_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.prod
    depends_on:
      - postgres

volumes:
  postgres_data:
