name: Auto deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Generate Prisma client
        run: npx prisma generate
        working-directory: backend

      - name: Build backend
        run: npm run build
        working-directory: backend

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Add VPS to known hosts
        run: ssh-keyscan -H 68.183.141.196 >> ~/.ssh/known_hosts

      - name: Pull latest code
        run: ssh root@68.183.141.196 "cd /root/SketchPals && git pull"
